[build]
  publish = "dist"
  command = "npm run build"
  environment = { SECRETS_SCAN_SMART_DETECTION_ENABLED = "false" }

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
